# Generated by Django 5.2.5 on 2025-11-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
